version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: allra-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: allra_ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: allra-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
