spring:
  application:
    name: ecommerce
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: qwertyuioppaqwertyuioppasdfghjklzxcvbnmsdfghjklzxcvbnm
