spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://localhost:3306/allra_ecommerce?serverTimezone=Asia/Seoul
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

